function test() {
    throw 'my_err'
}

test()